// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: livenstore_grpc/livenstore.proto

package livenstore_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type PublishEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_livenstore_grpc_livenstore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livenstore_grpc_livenstore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_livenstore_grpc_livenstore_proto_rawDescGZIP(), []int{0}
}

func (x *PublishEventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PublishEventRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// The response message containing the greetings
type PublishEventReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PublishEventReply) Reset() {
	*x = PublishEventReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_livenstore_grpc_livenstore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventReply) ProtoMessage() {}

func (x *PublishEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_livenstore_grpc_livenstore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventReply.ProtoReflect.Descriptor instead.
func (*PublishEventReply) Descriptor() ([]byte, []int) {
	return file_livenstore_grpc_livenstore_proto_rawDescGZIP(), []int{1}
}

func (x *PublishEventReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_livenstore_grpc_livenstore_proto protoreflect.FileDescriptor

var file_livenstore_grpc_livenstore_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x3d, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x23, 0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x63, 0x0a, 0x0a, 0x4c, 0x69, 0x76, 0x65, 0x6e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x55, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x12, 0x24, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28,
	0x6c, 0x69, 0x76, 0x65, 0x6e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x65, 0x76, 0x72, 0x61, 0x72,
	0x64, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_livenstore_grpc_livenstore_proto_rawDescOnce sync.Once
	file_livenstore_grpc_livenstore_proto_rawDescData = file_livenstore_grpc_livenstore_proto_rawDesc
)

func file_livenstore_grpc_livenstore_proto_rawDescGZIP() []byte {
	file_livenstore_grpc_livenstore_proto_rawDescOnce.Do(func() {
		file_livenstore_grpc_livenstore_proto_rawDescData = protoimpl.X.CompressGZIP(file_livenstore_grpc_livenstore_proto_rawDescData)
	})
	return file_livenstore_grpc_livenstore_proto_rawDescData
}

var file_livenstore_grpc_livenstore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_livenstore_grpc_livenstore_proto_goTypes = []any{
	(*PublishEventRequest)(nil), // 0: livenstore_grpc.PublishEventRequest
	(*PublishEventReply)(nil),   // 1: livenstore_grpc.PublishEventReply
}
var file_livenstore_grpc_livenstore_proto_depIdxs = []int32{
	0, // 0: livenstore_grpc.Livenstore.Publish:input_type -> livenstore_grpc.PublishEventRequest
	1, // 1: livenstore_grpc.Livenstore.Publish:output_type -> livenstore_grpc.PublishEventReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_livenstore_grpc_livenstore_proto_init() }
func file_livenstore_grpc_livenstore_proto_init() {
	if File_livenstore_grpc_livenstore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_livenstore_grpc_livenstore_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PublishEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_livenstore_grpc_livenstore_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PublishEventReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_livenstore_grpc_livenstore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livenstore_grpc_livenstore_proto_goTypes,
		DependencyIndexes: file_livenstore_grpc_livenstore_proto_depIdxs,
		MessageInfos:      file_livenstore_grpc_livenstore_proto_msgTypes,
	}.Build()
	File_livenstore_grpc_livenstore_proto = out.File
	file_livenstore_grpc_livenstore_proto_rawDesc = nil
	file_livenstore_grpc_livenstore_proto_goTypes = nil
	file_livenstore_grpc_livenstore_proto_depIdxs = nil
}
