// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: livenstore_grpc/livenstore.proto

package livenstore_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Livenstore_Publish_FullMethodName   = "/livenstore_grpc.Livenstore/Publish"
	Livenstore_EventByID_FullMethodName = "/livenstore_grpc.Livenstore/EventByID"
)

// LivenstoreClient is the client API for Livenstore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LivenstoreClient interface {
	Publish(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventReply, error)
	EventByID(ctx context.Context, in *EventByIDRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type livenstoreClient struct {
	cc grpc.ClientConnInterface
}

func NewLivenstoreClient(cc grpc.ClientConnInterface) LivenstoreClient {
	return &livenstoreClient{cc}
}

func (c *livenstoreClient) Publish(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventReply)
	err := c.cc.Invoke(ctx, Livenstore_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *livenstoreClient) EventByID(ctx context.Context, in *EventByIDRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, Livenstore_EventByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LivenstoreServer is the server API for Livenstore service.
// All implementations must embed UnimplementedLivenstoreServer
// for forward compatibility.
type LivenstoreServer interface {
	Publish(context.Context, *PublishEventRequest) (*PublishEventReply, error)
	EventByID(context.Context, *EventByIDRequest) (*EventResponse, error)
	mustEmbedUnimplementedLivenstoreServer()
}

// UnimplementedLivenstoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLivenstoreServer struct{}

func (UnimplementedLivenstoreServer) Publish(context.Context, *PublishEventRequest) (*PublishEventReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedLivenstoreServer) EventByID(context.Context, *EventByIDRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventByID not implemented")
}
func (UnimplementedLivenstoreServer) mustEmbedUnimplementedLivenstoreServer() {}
func (UnimplementedLivenstoreServer) testEmbeddedByValue()                    {}

// UnsafeLivenstoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LivenstoreServer will
// result in compilation errors.
type UnsafeLivenstoreServer interface {
	mustEmbedUnimplementedLivenstoreServer()
}

func RegisterLivenstoreServer(s grpc.ServiceRegistrar, srv LivenstoreServer) {
	// If the following call pancis, it indicates UnimplementedLivenstoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Livenstore_ServiceDesc, srv)
}

func _Livenstore_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivenstoreServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Livenstore_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivenstoreServer).Publish(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Livenstore_EventByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivenstoreServer).EventByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Livenstore_EventByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivenstoreServer).EventByID(ctx, req.(*EventByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Livenstore_ServiceDesc is the grpc.ServiceDesc for Livenstore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Livenstore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livenstore_grpc.Livenstore",
	HandlerType: (*LivenstoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Livenstore_Publish_Handler,
		},
		{
			MethodName: "EventByID",
			Handler:    _Livenstore_EventByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livenstore_grpc/livenstore.proto",
}
